CREATE DATABASE IF NOT EXISTS django;
GRANT ALL PRIVILEGES ON django.* TO 'django'@'%' IDENTIFIED BY 'django';
GRANT SELECT ON mysql.* TO 'django'@'%' IDENTIFIED BY 'django';
FLUSH PRIVILEGES;
FLUSH TABLES;
